
server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        default_schema: public
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600
  refreshable-duration: 36000

brevo:
  api:
    key: "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"


info:
  admin:
    enabled: true
    role-code: ADMIN
    role-name: ADMIN
    role-description: Default administrator role
    username: admin
    password: admin
    email: admin@example.com
    first-name: Lê
    last-name: Vĩnh Nguyên
    gender: MALE
    phone-number: "0868369069"
    date-of-birth: 2004-06-01
    address: "Soc Trang"

app:
  api-key:
    name: X-API-Key
    value: m-gWgnoHeQ5THyLxxxFdIXpEfvJbqb62toA4QT-8QSHqNpL0r_djsWCq-aBwh569